# Publish
- name: Publish package to Sonatype
  if: github.ref == 'refs/heads/master'
  env:
    ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USER }}
    ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
    SONATYPE_GPG_KEYID: ${{ secrets.SONATYPE_GPG_KEYID }}
    SONATYPE_GPG_PASSWORD: ${{ secrets.SONATYPE_GPG_PASSWORD }}
    SONATYPE_GPG_FILE: ${{ secrets.SONATYPE_GPG_FILE }}
  run: |
    echo "signing.keyId=${SONATYPE_GPG_KEYID}" > ~/.gradle/gradle.properties
    echo "signing.password=${SONATYPE_GPG_PASSWORD}" >> ~/.gradle/gradle.properties
    echo "signing.secretKeyRingFile=${HOME}/.gradle/secring.gpg" >> ~/.gradle/gradle.properties
    echo ${SONATYPE_GPG_FILE} | base64 -d > ~/.gradle/secring.gpg
    ./gradlew publishToSonatype

# Release
- name: Release package to Maven Central
  if: startsWith(github.ref, 'refs/tags/v')
  env:
    ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USER }}
    ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
    SONATYPE_GPG_KEYID: ${{ secrets.SONATYPE_GPG_KEYID }}
    SONATYPE_GPG_PASSWORD: ${{ secrets.SONATYPE_GPG_PASSWORD }}
    SONATYPE_GPG_FILE: ${{ secrets.SONATYPE_GPG_FILE }}
  run: |
    echo "signing.keyId=${SONATYPE_GPG_KEYID}" > ~/.gradle/gradle.properties
    echo "signing.password=${SONATYPE_GPG_PASSWORD}" >> ~/.gradle/gradle.properties
    echo "signing.secretKeyRingFile=${HOME}/.gradle/secring.gpg" >> ~/.gradle/gradle.properties
    echo ${SONATYPE_GPG_FILE} | base64 -d > ~/.gradle/secring.gpg
    ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository